FROM ghcr.io/bjia56/armv7l-wheel-builder:main

RUN pip3.8 install -U setuptools wheel
RUN pip3.9 install -U setuptools wheel

RUN ln -s /usr/local/bin/pip3.8 /usr/local/bin/pip
RUN pip install auditwheel
