name: Build @scrypted/arlo dependencies

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  stage1:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (stage 1)
        uses: docker/build-push-action@v3
        with:
          context: ./arlo
          file: ./arlo/Dockerfile.stage1
          push: false
          platforms: linux/armhf
          tags: stage1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
          outputs: type=docker,dest=/tmp/stage1.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stage1
          path: /tmp/stage1.tar

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 6000
          swap-size-mb: 50000
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: stage1
          path: /tmp

      - name: Load image
        run: |
          docker system prune -a
          docker load --input /tmp/stage1.tar
          rm /tmp/stage1.tar
          docker image ls -a

      - name: Push image to local registry
        run: |
          docker image tag stage1:latest localhost:5000/stage1:latest
          docker image push localhost:5000/stage1:latest

      - name: Build Docker image (stage 2)
        uses: docker/build-push-action@v3
        with:
          context: ./arlo
          file: ./arlo/Dockerfile.stage2
          build-contexts: stage1=docker-image://localhost:5000/stage1:latest
          push: false
          platforms: linux/armhf
          tags: stage2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
          outputs: type=docker,dest=/tmp/stage2.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stage2
          path: /tmp/stage2.tar

